### ISSUE TITLE
URI malformed since upgradeing HomeBridge to latest

### ISSUE THREAD

**Issue by joelhinch** [yenoiwesa/homebridge-daikin-airbase#53]
[6/30/2023, 3:51:41 PM] [Daikin Airbase] URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at parse (/homebridge/node_modules/homebridge-daikin-airbase/src/constants.js:83:29)
    at /homebridge/node_modules/homebridge-daikin-airbase/src/airbase-controller.js:86:45
    at Array.reduce (<anonymous>)
    at DaikinAircon.normalizeResponse (/homebridge/node_modules/homebridge-daikin-airbase/src/airbase-controller.js:81:36)
    at DaikinAircon.sendRequest (/homebridge/node_modules/homebridge-daikin-airbase/src/airbase-controller.js:137:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DaikinAircon.exec [as getRawZoneSetting] (/homebridge/node_modules/homebridge-daikin-airbase/src/utils.js:15:20)
    at DaikinAircon.init (/homebridge/node_modules/homebridge-daikin-airbase/src/airbase-controller.js:164:35)
    at RetryOperation._fn (/homebridge/node_modules/homebridge-daikin-airbase/src/daikin-airbase-platform.js:106:21)
[6/30/2023, 3:51:41 PM] [Daikin Airbase] Found 0 devices

any ideas?

**Comment by yenoiwesa** [comment]
My bet is on wrong configuration.
What does the platform configuration JSON looks like?

**Comment by yenoiwesa** [comment]
Any update @joelhinch ?

**Comment by yenoiwesa** [comment]
I'll close the issue for now, feel free to reopen when you have more details.
